language: python

python:
    - 3.7
branches:
  only:
    - develop
    - master

before_install:
    - python --version
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - source $HOME/.poetry/env

install:
    - poetry install

script:
    - poetry run python -m nose . --with-xunit --with-coverage --cover-erase --cover-package=pandas_aws
    - poetry export -f requirements.txt > requirements.txt

after_success:
    - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: bash deploy.sh develop
    on:
      branch: develop
  - provider: script
    script: bash deploy.sh master
    on:
      branch: master
