name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for publishing this issue, you rock!
        pr-message: 'Thank you for your PR, it''s amazing to have you on board. I''l keep you informed.'
